# Generated by Django 5.1.3 on 2026-03-29 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenominationLiquidationAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_remarks', models.TextField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denomination_liquidation_requests', to='Church.church')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_denomination_liquidation_requests', to=settings.AUTH_USER_MODEL)),
                ('denomination_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denomination_liquidation_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_denomination_liquidation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denomination Liquidation Access Request',
                'verbose_name_plural': 'Denomination Liquidation Access Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
