# Generated by Django 5.1.3 on 2026-04-09 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0003_denominationliquidationaccessrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchapplication',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Church Application', 'verbose_name_plural': 'Church Applications'},
        ),
        migrations.AlterField(
            model_name='churchapplication',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_church_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
