"""
Django settings for MainProject project.
Generated by 'django-admin startproject' using Django 5.1.1.
"""

import logging
import os
from pathlib import Path

import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# CORE / SECURITY
# =========================
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY is not set.")

DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

render_hostname = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if render_hostname and render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_hostname)

extra_hosts = os.getenv("ALLOWED_HOSTS", "")
if extra_hosts:
    ALLOWED_HOSTS.extend(
        [host.strip() for host in extra_hosts.split(",") if host.strip()]
    )

CSRF_TRUSTED_ORIGINS = []

if render_hostname:
    CSRF_TRUSTED_ORIGINS.append(f"https://{render_hostname}")

extra_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if extra_csrf_origins:
    CSRF_TRUSTED_ORIGINS.extend(
        [origin.strip() for origin in extra_csrf_origins.split(",") if origin.strip()]
    )

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# =========================
# APPLICATIONS
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    "Register",
    "Process",
    "Church",
    "ai_analytics.apps.AiAnalyticsConfig",
]

AUTH_USER_MODEL = "Register.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "MainProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MainProject.wsgi.application"


# =========================
# OPENAI
# =========================
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_BUDGET_MODEL = os.getenv("OPENAI_BUDGET_MODEL", "gpt-5.4")


# =========================
# DATABASE
# =========================
DATABASE_URL = (os.getenv("DATABASE_URL") or "").strip()
DB_SSL_CA = (os.getenv("DB_SSL_CA") or "").strip()

if DATABASE_URL:
    if not DATABASE_URL.startswith("mysql://"):
        raise ValueError("DATABASE_URL must start with mysql:// for this project.")

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            engine="django.db.backends.mysql",
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"].update({
        "charset": "utf8mb4",
        "ssl_mode": "REQUIRED",
    })

    if DB_SSL_CA:
        DATABASES["default"]["OPTIONS"]["ssl"] = {
            "ca": DB_SSL_CA,
        }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME", "church1"),
            "USER": os.getenv("DB_USER", "root"),
            "PASSWORD": os.getenv("DB_PASSWORD", "root"),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
            },
        }
    }

# IMPORTANT:
# Do not redefine DATABASES anywhere below this block.

settings_logger = logging.getLogger("django")
try:
    db_info = DATABASES["default"]
    settings_logger.warning(
        "SETTINGS DB TARGET | engine=%s | host=%s | port=%s | name=%s | user=%s",
        db_info.get("ENGINE"),
        db_info.get("HOST"),
        db_info.get("PORT"),
        db_info.get("NAME"),
        db_info.get("USER"),
    )
except Exception:
    pass


# =========================
# PASSWORD VALIDATION
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# =========================
# INTERNATIONALIZATION
# =========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Manila"
USE_I18N = True
USE_TZ = True


# =========================
# STATIC / MEDIA
# =========================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATIC_DIR = BASE_DIR / "static"
if STATIC_DIR.exists():
    STATICFILES_DIRS = [STATIC_DIR]
else:
    STATICFILES_DIRS = []

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# =========================
# EMAIL
# =========================
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER or "webmaster@localhost"
)


# =========================
# THIRD-PARTY INTEGRATIONS
# =========================
MAYA_PUBLIC_KEY = os.getenv("MAYA_PUBLIC_KEY", "")
MAYA_SECRET_KEY = os.getenv("MAYA_SECRET_KEY", "")
MAYA_CHECKOUT_CREATE_URL = "https://pg.maya.ph/checkout/v1/checkouts"
MAYA_WEBHOOK_SECRET = os.getenv("MAYA_WEBHOOK_SECRET", "")

CHK_PUBLIC_KEY = os.getenv("CHK_PUBLIC_KEY", "")
CHK_SECRET_KEY = os.getenv("CHK_SECRET_KEY", "")
CHK_PAYMENTS_URL = "https://api.checkout.com/payments"

if os.name == "nt":
    TESSERACT_CMD = os.getenv(
        "TESSERACT_CMD",
        r"C:\Program Files\Tesseract-OCR\tesseract.exe"
    )
else:
    TESSERACT_CMD = os.getenv("TESSERACT_CMD", "/usr/bin/tesseract")


# =========================
# DEFAULT PK
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"