# Generated by Django 5.1.3 on 2026-03-05 13:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Church', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='references/approved/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryBankMovementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='temp_bank_movements/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryExpenseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='temp_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryOtherIncomeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='temp_other_income/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_date', models.DateField(blank=True, help_text='Transactions on or before this date cannot be added or edited.', null=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_settings', to='Church.church')),
            ],
        ),
        migrations.CreateModel(
            name='DonationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_restricted', models.BooleanField(default=False, help_text='Check this if money in this category is reserved for a specific purpose (e.g., Building Fund) and cannot be used for general expenses.', verbose_name='Restricted Fund?')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_categories', to='Church.church')),
            ],
            options={
                'verbose_name_plural': 'Donation Categories',
                'unique_together': {('name', 'church')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_transfer', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('is_restricted', models.BooleanField(default=False, help_text='If True, this expense category is tied to a specific restricted fund.')),
                ('restricted_source', models.CharField(blank=True, choices=[('DONATION', 'Donation Fund'), ('OTHER_INCOME', 'Other Income Fund')], max_length=20, null=True)),
                ('restricted_category_id', models.BigIntegerField(blank=True, help_text='ID of DonationCategory or OtherIncomeCategory this expense category belongs to.', null=True)),
                ('fund_key', models.CharField(db_index=True, default='U', max_length=30)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='Church.church')),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Details about the expense (e.g. Invoice #, Specific items)', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='expenses/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('receipt_image', models.ImageField(blank=True, help_text='Upload a clear photo of the Official Receipt.', null=True, upload_to='expense_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='Church.church')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='Register.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Living Stone Evangelical Free Church', max_length=200)),
                ('subtitle', models.TextField(default='Disciple making Disciples')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home_hero/')),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_content', to='Church.church')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.SlugField(help_text='Short identifier (e.g., mens, womens, youth)')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority_score', models.IntegerField(default=5, help_text='1-10 Scale: Higher score means higher funding priority in AI optimization.')),
                ('min_monthly_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hard constraint: The minimum amount this ministry REQUIRES to operate.', max_digits=12)),
                ('max_monthly_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Optional constraint: The maximum amount this ministry can effectively use.', max_digits=12, null=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministries', to='Church.church')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MinistryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(0, 'Whole Year (Lump Sum)'), (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=0)),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, no new funds can be released from this budget.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministry_budgets', to='Church.church')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='Register.ministry')),
            ],
            options={
                'ordering': ['-year', '-month', 'ministry__name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetReleaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_released', models.DateField(help_text='Date the funds are needed')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_release_requests', to='Church.church')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register.ministry')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_requests', to='Register.ministrybudget')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='The live physical cash available for this budget.', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Church.church')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register.ministry')),
                ('budget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_account', to='Register.ministrybudget')),
            ],
        ),
        migrations.CreateModel(
            name='OtherIncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_restricted', models.BooleanField(default=False, help_text='Check if this income is restricted for specific use.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_income_categories', to='Church.church')),
            ],
            options={
                'verbose_name_plural': 'Other Income Categories',
            },
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='other_income/')),
                ('receipt_image', models.ImageField(blank=True, help_text='Upload a clear photo of the receipt/supporting document.', null=True, upload_to='other_income_receipts/')),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('ocr_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_incomes', to='Church.church')),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='Register.otherincomecategory')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, default='', max_length=30)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('municipality_or_city', models.CharField(blank=True, default='', max_length=100)),
                ('barangay', models.CharField(blank=True, default='', max_length=100)),
                ('purok', models.CharField(blank=True, default='', max_length=100)),
                ('birthdate', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('DenominationAdmin', 'DenominationAdmin'), ('ChurchAdmin', 'ChurchAdmin'), ('Treasurer', 'Treasurer'), ('Pastor', 'Pastor'), ('Member', 'Member')], max_length=20)),
                ('year_term', models.CharField(blank=True, choices=[('1', '1 Year'), ('2', '2 Years')], max_length=1, null=True)),
                ('organization', models.CharField(blank=True, choices=[('Mens', "Men's Ministry"), ('Womens', "Women's Ministry"), ('YoungPeople', 'Young People')], max_length=20, null=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Church.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('denomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Church.denomination')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tithe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(default='No description', max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='tithes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tithes', to='Church.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tithes', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_tithes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tithes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThankYouLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.approvedreference')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thank_you_letters_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thank_you_letters_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_released', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('amount_returned', models.DecimalField(decimal_places=2, default=0.0, help_text='Excess cash returned after liquidation.', max_digits=12)),
                ('is_liquidated', models.BooleanField(default=False)),
                ('liquidated_date', models.DateField(blank=True, null=True)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('approved_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_release', to='Register.budgetreleaserequest')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='released_budgets', to='Register.ministrybudget')),
                ('budget_return_income', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_budget_return', to='Register.otherincome')),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='released_budgets', to='Church.church')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register.ministry')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-released_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PendingReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='references/pending/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_references', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='otherincome',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_other_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_other_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(default='No description', max_length=200)),
                ('proof_document', models.ImageField(blank=True, help_text='Upload a photo of the Tally Sheet or Deposit Slip.', null=True, upload_to='offering_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='Church.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offerings', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_offering', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ministrybudget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ministrybudget',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ministry',
            name='assigned_requester',
            field=models.ForeignKey(blank=True, help_text='The user authorized to request budgets for this ministry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ministries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ministry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ministry',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministries_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExpenseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_type', models.CharField(choices=[('UNRESTRICTED', 'Unrestricted'), ('RESTRICTED', 'Restricted')], max_length=12)),
                ('fund_key', models.CharField(db_index=True, max_length=32)),
                ('restricted_source', models.CharField(blank=True, choices=[('DONATION', 'Donation Fund'), ('OTHER_INCOME', 'Other Income Fund')], max_length=20, null=True)),
                ('restricted_category_id', models.BigIntegerField(blank=True, null=True)),
                ('fund_name', models.CharField(default='Unrestricted', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_allocations', to='Church.church')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='Register.expense')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_allocations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor', models.CharField(blank=True, max_length=100, null=True)),
                ('other_donations_type', models.CharField(blank=True, max_length=100, null=True)),
                ('donations_date', models.DateField(default=django.utils.timezone.now)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='Church.church')),
                ('donations_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='Register.donationcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_donations', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_donations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeclinedReleaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('date_released', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('declined_reason', models.CharField(blank=True, max_length=255)),
                ('declined_at', models.DateTimeField(auto_now_add=True)),
                ('original_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decline_records', to='Register.budgetreleaserequest')),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_release_requests', to='Register.ministrybudget')),
                ('declined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_by_records', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_budget_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-declined_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashBankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('direction', models.CharField(choices=[('CASH_TO_BANK', 'Cash → Bank (Deposit)'), ('BANK_TO_CASH', 'Bank → Cash (Withdrawal)'), ('BANK_TO_BANK', 'Bank → Bank (Transfer)'), ('DIRECT_BANK_RECEIPT', 'Direct to Bank (Income)'), ('BANK_PAID_EXPENSE', 'Paid from Bank (Expense)')], db_index=True, max_length=32)),
                ('source_type', models.CharField(choices=[('TITHE', 'Tithe'), ('OFFERING', 'Offering'), ('DONATION', 'Donation'), ('OTHER_INCOME', 'Other Income'), ('EXPENSE', 'Expense'), ('TRANSFER_ONLY', 'Transfer Only')], default='TRANSFER_ONLY', max_length=24)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('reference_no', models.CharField(blank=True, default='', max_length=64)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='bank_movements/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], db_index=True, default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_bank_movements', to='Church.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_movements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='budgetreleaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetreleaserequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_incurred', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_proof', models.FileField(blank=True, help_text='Upload an image or PDF of the receipt.', null=True, upload_to='receipts/%Y/%m/')),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_expenses', to='Church.church')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register.ministry')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='Register.releasedbudget')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_incurred', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Main Bank Account', max_length=100)),
                ('account_name', models.CharField(default='Church Account', help_text='e.g. Living Stone Church Main Fund', max_length=100)),
                ('account_number', models.CharField(help_text='Enter the official bank account number.', max_length=50, unique=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('verification_image', models.ImageField(help_text='Upload a screenshot or photo of the bank statement/balance.', upload_to='bank_verification/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='Church.church')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('object_model', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=60)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedReleaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_released', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_release_requests', to='Church.church')),
                ('approved_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_ticket', to='Register.budgetreleaserequest')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register.ministry')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_release_requests', to='Register.ministrybudget')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-approved_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='approvedreference',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_references', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvedreference',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_references_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_restricted', False)), fields=('church', 'name'), name='uniq_unrestricted_expensecategory_name_per_church'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_restricted', True)), fields=('church', 'fund_key'), name='uniq_restricted_expensecategory_fund_key_per_church'),
        ),
        migrations.AlterUniqueTogether(
            name='otherincomecategory',
            unique_together={('name', 'church')},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='Register_cu_user_ty_efbf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['church'], name='Register_cu_church__244e91_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['denomination'], name='Register_cu_denomin_fb27ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='ministrybudget',
            constraint=models.UniqueConstraint(condition=models.Q(('month', 0)), fields=('church', 'ministry', 'year'), name='uniq_yearly_pool_church_ministry_year'),
        ),
        migrations.AddConstraint(
            model_name='ministrybudget',
            constraint=models.UniqueConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), fields=('church', 'ministry', 'year', 'month'), name='uniq_monthly_budget_church_ministry_year_month'),
        ),
        migrations.AddConstraint(
            model_name='ministrybudget',
            constraint=models.CheckConstraint(condition=models.Q(('month', 0), models.Q(('month__gte', 1), ('month__lte', 12)), _connector='OR'), name='chk_budget_month_0_or_1_12'),
        ),
        migrations.AddConstraint(
            model_name='ministry',
            constraint=models.UniqueConstraint(fields=('church', 'name'), name='unique_ministry_name_per_church'),
        ),
        migrations.AddConstraint(
            model_name='ministry',
            constraint=models.UniqueConstraint(fields=('church', 'code'), name='unique_ministry_code_per_church'),
        ),
        migrations.AddIndex(
            model_name='expenseallocation',
            index=models.Index(fields=['church', 'fund_key'], name='Register_ex_church__6b3f82_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseallocation',
            index=models.Index(fields=['church', 'fund_type'], name='Register_ex_church__ac9f21_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseallocation',
            index=models.Index(fields=['expense'], name='Register_ex_expense_4b2e73_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenseallocation',
            constraint=models.UniqueConstraint(fields=('expense', 'fund_key'), name='uniq_expense_fund_key'),
        ),
        migrations.AddIndex(
            model_name='cashbankmovement',
            index=models.Index(fields=['church', 'date'], name='Register_ca_church__faeb4f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbankmovement',
            index=models.Index(fields=['church', 'direction', 'date'], name='Register_ca_church__fc55e0_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbankmovement',
            index=models.Index(fields=['source_type', 'source_id'], name='Register_ca_source__4e76ee_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbankmovement',
            index=models.Index(fields=['church', 'status', 'date'], name='Register_ca_church__0a8050_idx'),
        ),
    ]
