# Generated by Django 5.1.3 on 2026-03-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedbudget',
            name='deduct_from',
            field=models.CharField(choices=[('cash', 'Physical Cash'), ('bank', 'Bank')], default='cash', help_text='Source of released funds: Physical Cash or Bank.', max_length=10),
        ),
    ]
