# Generated by Django 5.1.3 on 2026-03-13 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_releasedbudget_deduct_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexpense',
            name='paid_from',
            field=models.CharField(choices=[('cash', 'Physical Cash'), ('bank', 'Bank')], default='cash', help_text='How this ministry expense was paid. For audit/reference only.', max_length=10),
        ),
        migrations.AddField(
            model_name='releasedbudget',
            name='bank_return_expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_budget_return_bank_transfer', to='Register.expense'),
        ),
        migrations.AddField(
            model_name='releasedbudget',
            name='return_to',
            field=models.CharField(choices=[('cash', 'Physical Cash'), ('bank', 'Bank')], default='cash', help_text='Where the unused amount is returned after liquidation.', max_length=10),
        ),
    ]
