# Generated by Django 5.1.3 on 2026-03-13 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0002_initial'),
        ('Register', '0003_budgetexpense_paid_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField()),
                ('direction', models.CharField(choices=[('IN', 'Cash In'), ('OUT', 'Cash Out')], default='IN', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(default='BUDGET_RETURN', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='Church.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-txn_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='releasedbudget',
            name='cash_return_txn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_budget_return_cash', to='Register.cashtransaction'),
        ),
    ]
