# Generated by Django 5.1.3 on 2026-03-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_cashtransaction_releasedbudget_cash_return_txn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbankmovement',
            name='source_type',
            field=models.CharField(choices=[('TITHE', 'Tithe'), ('OFFERING', 'Offering'), ('DONATION', 'Donation'), ('OTHER_INCOME', 'Other Income'), ('EXPENSE', 'Expense'), ('TRANSFER_ONLY', 'Transfer Only'), ('ADJUSTMENT', 'Adjustment')], default='TRANSFER_ONLY', max_length=24),
        ),
    ]
