# Generated by Django 5.1.3 on 2026-03-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_alter_cashbankmovement_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasedbudget',
            name='bank_return_expense',
        ),
    ]
