# Generated by Django 5.1.3 on 2026-03-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_remove_releasedbudget_bank_return_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='ocr_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='ocr_text',
            field=models.TextField(
                blank=True,
                help_text='Extracted OCR text from uploaded receipt.',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='donations',
            name='receipt_image',
            field=models.ImageField(
                blank=True,
                help_text='Optional image version of the receipt.',
                null=True,
                upload_to='donations/receipts/%Y/%m/'
            ),
        ),
    ]