# Generated by Django 5.1.3 on 2026-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0002_initial'),
        ('Register', '0007_temporarydonationfile_donations_file_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ministrybudget',
            index=models.Index(fields=['church', 'year', 'month'], name='Register_mi_church__399a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='ministrybudget',
            index=models.Index(fields=['church', 'ministry', 'year'], name='Register_mi_church__70d4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='ministrybudget',
            index=models.Index(fields=['church', 'is_active'], name='Register_mi_church__3de419_idx'),
        ),
        migrations.AddConstraint(
            model_name='ministrybudget',
            constraint=models.CheckConstraint(condition=models.Q(('amount_allocated__gte', 0)), name='chk_budget_amount_non_negative'),
        ),
    ]
