# Generated by Django 5.1.3 on 2026-03-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0008_temporarydonationfile_donations_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryDonationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='temp/donations/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='enable_expense_fraud_detection',
            field=models.BooleanField(default=False, help_text='Enable AI fraud detection for expense receipt uploads. Default is OFF.'),
        ),
        migrations.AddField(
            model_name='donations',
            name='file',
            field=models.FileField(blank=True, help_text='Upload PDF or image proof/receipt.', null=True, upload_to='donations/files/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='lock_date',
            field=models.DateField(blank=True, help_text='Transactions before this date cannot be added or edited.', null=True),
        ),
        migrations.AlterField(
            model_name='ministrybudget',
            name='month',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
