# Generated by Django 5.1.3 on 2026-03-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0011_add_other_income_fraud_detection_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='enable_donation_fraud_detection',
            field=models.BooleanField(default=False, help_text='Enable AI fraud detection for donation proof uploads. Default is OFF.'),
        ),
    ]
