# Generated by Django 5.1.3 on 2026-03-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0012_accountingsettings_enable_donation_fraud_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='enable_tithe_fraud_detection',
            field=models.BooleanField(default=False, help_text='Enable AI fraud detection for tithe proof uploads. Default is OFF.'),
        ),
    ]
