# Generated by Django 5.1.3 on 2026-03-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0013_accountingsettings_enable_tithe_fraud_detection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingsettings',
            options={'verbose_name': 'Accounting Setting', 'verbose_name_plural': 'Accounting Settings'},
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='enable_offering_fraud_detection',
            field=models.BooleanField(default=False, help_text='Enable AI fraud detection for offering proof uploads. Default is OFF.'),
        ),
    ]
