# Generated by Django 5.1.3 on 2026-03-26 00:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0014_alter_accountingsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offering',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Offering', 'verbose_name_plural': 'Offerings'},
        ),
        migrations.AddField(
            model_name='offering',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='offering',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_offerings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offering',
            name='proof_document',
            field=models.FileField(blank=True, help_text='Upload JPG, PNG, or PDF of the tally sheet, envelope summary, or deposit slip.', null=True, upload_to='offering_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
