# Generated by Django 5.1.3 on 2026-03-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0015_alter_offering_options_offering_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(default='Welcome to Church Financial Management System', max_length=200),
        ),
    ]
