# Generated by Django 5.1.3 on 2026-03-29 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0002_initial'),
        ('Register', '0016_alter_homepagecontent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenominationLiquidationAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denomination_liquidation_requests', to='Church.church')),
                ('denomination_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denomination_liquidation_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_denomination_liquidation_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
