# Generated by Django 5.1.3 on 2026-03-29 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0017_denominationliquidationaccessrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denominationliquidationaccessrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Denomination Liquidation Access Request', 'verbose_name_plural': 'Denomination Liquidation Access Requests'},
        ),
        migrations.AddField(
            model_name='denominationliquidationaccessrequest',
            name='close_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denominationliquidationaccessrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denominationliquidationaccessrequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_denomination_liquidation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='denominationliquidationaccessrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
