# Generated by Django 5.1.3 on 2026-03-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0018_alter_denominationliquidationaccessrequest_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DenominationLiquidationAccessRequest',
        ),
    ]
