# Generated by Django 5.1.3 on 2026-04-04 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0003_denominationliquidationaccessrequest'),
        ('Register', '0019_delete_denominationliquidationaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='denomination',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_content', to='Church.denomination'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='church',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_content', to='Church.church'),
        ),
    ]
