# Generated by Django 5.1.3 on 2026-04-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0020_homepagecontent_denomination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Treasurer', 'Treasurer'), ('Pastor', 'Pastor'), ('Member', 'Member')], max_length=20),
        ),
    ]
