# Generated by Django 5.1.3 on 2026-04-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0021_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('DenominationAdmin', 'DenominationAdmin'), ('ChurchAdmin', 'ChurchAdmin'), ('Treasurer', 'Treasurer'), ('Pastor', 'Pastor'), ('Member', 'Member')], max_length=20),
        ),
    ]
