# Generated by Django 5.1.3 on 2026-04-09 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0022_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donations',
            options={'ordering': ['-donations_date', '-id'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AddField(
            model_name='donations',
            name='donor_type',
            field=models.CharField(choices=[('member', 'Member'), ('non_member', 'Non-member'), ('anonymous', 'Anonymous')], default='anonymous', help_text='Select whether the donor is a member, non-member, or anonymous.', max_length=20),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donor',
            field=models.CharField(blank=True, help_text='Used only when donor type is Non-member.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Used only when donor type is Member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
