# Generated by Django 5.1.3 on 2026-04-09 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0023_alter_donations_options_donations_donor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donor',
            field=models.CharField(blank=True, help_text='Stores donor name for member and non-member donations.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Used when donor type is Member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
