# Generated by Django 5.1.3 on 2026-04-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Church', '0004_alter_churchapplication_options_and_more'),
        ('Register', '0024_alter_donations_donor_alter_donations_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['status'], name='Register_cu_status_fa6684_idx'),
        ),
    ]
