# Generated by Django 5.1.3 on 2026-04-11 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_customuser_indexes_if_exist(apps, schema_editor):
    CustomUser = apps.get_model('Register', 'CustomUser')
    table_name = CustomUser._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)

    existing_constraints = set(constraints.keys())

    indexes_to_remove = [
        ('Register_cu_church__244e91_idx', ['church']),
        ('Register_cu_denomin_fb27ef_idx', ['denomination']),
    ]

    for index_name, fields in indexes_to_remove:
        if index_name in existing_constraints:
            schema_editor.remove_index(
                CustomUser,
                models.Index(fields=fields, name=index_name),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0025_customuser_status_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_customuser_indexes_if_exist,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='customuser',
                    name='Register_cu_church__244e91_idx',
                ),
                migrations.RemoveIndex(
                    model_name='customuser',
                    name='Register_cu_denomin_fb27ef_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='disabled_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='disabled_users',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='customuser',
            name='inactivity_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]