# Generated by Django 5.1.1 on 2026-04-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0026_remove_customuser_register_cu_church__244e91_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, help_text='Vendor or payee name for this expense (optional).', max_length=255, null=True),
        ),
    ]
