# Generated by Django 5.1.3 on 2026-03-05 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizerRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_id', models.IntegerField(db_index=True)),
                ('mode', models.CharField(max_length=20)),
                ('reference_year', models.IntegerField(blank=True, null=True)),
                ('timeframe', models.CharField(max_length=10)),
                ('pool_used_monthly', models.DecimalField(decimal_places=2, max_digits=14)),
                ('priorities_used', models.JSONField(default=dict)),
                ('allocations_result', models.JSONField(default=dict)),
                ('ministry_constraints', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['church_id', 'created_at'], name='ai_analytic_church__08570a_idx'), models.Index(fields=['church_id', 'reference_year'], name='ai_analytic_church__10e8d6_idx')],
            },
        ),
    ]
